---
- hosts: LAMP
  become: true
  vars_files:
  - vars/vars.yml
  
  tasks:
  
  - name: Deploy LAMP
    ansible.builtin.include_role:  
      name: deploy_LAMP

  - name: Install unzip
    become: true
    ansible.builtin.apt: 
      name: unzip
      update_cache: yes
      state: latest
  
  - name: Create document root
    ansible.builtin.file:
      path: "/var/www/{{ http_host }}"
      state: directory

  - name: Download and unpack php-mysql-crud
    ansible.builtin.unarchive:
      src: https://github.com/FaztWeb/php-mysql-crud/archive/refs/heads/master.zip
      dest: "/var/www/{{ http_host }}"
      remote_src: yes

  - name: Set up DB config
    ansible.builtin.template:
      src: "files/db.php.j2"
      dest: "/var/www/{{ http_host }}/php-mysql-crud-master/db.php"

  - name: Set up Apache VirtualHost
    ansible.builtin.template:
      src: "files/apache.conf.j2"
      dest: "/etc/apache2/sites-available/{{ http_conf }}"

  - name: Enable new site
    ansible.builtin.shell: /usr/sbin/a2ensite {{ http_conf }}

  - name: Disable default Apache site
    ansible.builtin.shell: /usr/sbin/a2dissite 000-default.conf
    notify:
    - Restart Apache Debian          

- hosts: DATABASE
  vars_files:
    - vars/vars.yml
  
  tasks:
  
  - name: Deploy LAMP
    ansible.builtin.include_role:  
      name: deploy_MySQL
 
  - name: Copy script.sql file to database host
    ansible.builtin.template:
      src: "files/script.sql"
      dest: "/tmp"
  
  - name: Import script.sql file / Create database and table 
    community.mysql.mysql_db:
      state: import
      name: all
      login_user: root
      login_password: "{{ mysql_root_password }}"
      target: /tmp/script.sql
...