---
- hosts: LAMP
  vars_files:
  - vars/vars.yml
  tasks:
  
  - name: Deploy LAMP
    ansible.builtin.include_role:  
      name: deploy_LAMP
  
  - name: Deploy APP
    ansible.builtin.include_role:  
      name: deploy_APP

- hosts: DATABASE
  vars_files:
  - vars/vars.yml
  tasks:
  
  - name: Deploy MySQL
    ansible.builtin.include_role:  
      name: deploy_MySQL

  - name: Prepare DB
    ansible.builtin.include_role:  
      name: deploy_APP
...