- name: Install Apache
  become: true
  ansible.builtin.apt: 
    name: apache2
    update_cache: yes
    state: latest

- name: Start Apache2 and Enable it on the every boot
  service:
    name: apache2
    state: started
    enabled: yes

- name: Install PHP
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - php
    - php-mysql
    - libapache2-mod-php
    - php-curl
    - php-gd
    - php-mbstring
    - php-xml
    - php-xmlrpc
    - php-soap
    - php-intl
    - php-zip